"""empty message

Revision ID: 8bcf1fa6d1fd
Revises: 
Create Date: 2025-11-25 10:21:13.905347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bcf1fa6d1fd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sys_roles', schema=None) as batch_op:
        batch_op.drop_index('ix_sys_roles_seq')

    op.drop_table('sys_roles')
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.drop_index('ix_todos_id')
        batch_op.drop_index('ix_todos_title')

    op.drop_table('todos')
    op.drop_table('t_question')
    op.drop_table('user')
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_index('ix_question_id')

    op.drop_table('question')
    op.drop_table('sys_role_menu')
    with op.batch_alter_table('sys_menus', schema=None) as batch_op:
        batch_op.drop_index('ix_sys_menus_seq')

    op.drop_table('sys_menus')
    op.drop_table('t_answer')
    with op.batch_alter_table('sys_users', schema=None) as batch_op:
        batch_op.drop_index('ix_sys_users_seq')

    op.drop_table('sys_users')
    with op.batch_alter_table('sys_boards', schema=None) as batch_op:
        batch_op.drop_index('ix_sys_boards_seq')

    op.drop_table('sys_boards')
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.drop_index('ix_answer_id')

    op.drop_table('answer')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('create_date', sa.DATETIME(), nullable=False),
    sa.Column('question_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], name='fk_answer_question_id_question'),
    sa.PrimaryKeyConstraint('id', name='pk_answer')
    )
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.create_index('ix_answer_id', ['id'], unique=False)

    op.create_table('sys_boards',
    sa.Column('seq', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.VARCHAR(length=128), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('use_yn', sa.VARCHAR(length=1), nullable=True),
    sa.Column('create_dt', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('seq')
    )
    with op.batch_alter_table('sys_boards', schema=None) as batch_op:
        batch_op.create_index('ix_sys_boards_seq', ['seq'], unique=False)

    op.create_table('sys_users',
    sa.Column('seq', sa.INTEGER(), nullable=False),
    sa.Column('client_id', sa.VARCHAR(length=32), nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('user_nm', sa.VARCHAR(length=32), nullable=False),
    sa.Column('email', sa.VARCHAR(length=256), nullable=False),
    sa.Column('password', sa.VARCHAR(length=128), nullable=False),
    sa.Column('tel_phone', sa.VARCHAR(length=128), nullable=True),
    sa.Column('cell_phone', sa.VARCHAR(length=128), nullable=True),
    sa.Column('role_id', sa.INTEGER(), nullable=True),
    sa.Column('use_yn', sa.VARCHAR(length=1), nullable=True),
    sa.Column('created_dt', sa.DATETIME(), nullable=True),
    sa.Column('updated_dt', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['sys_roles.seq'], ),
    sa.PrimaryKeyConstraint('seq')
    )
    with op.batch_alter_table('sys_users', schema=None) as batch_op:
        batch_op.create_index('ix_sys_users_seq', ['seq'], unique=False)

    op.create_table('t_answer',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('create_date', sa.DATETIME(), nullable=False),
    sa.Column('question_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['t_question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sys_menus',
    sa.Column('seq', sa.INTEGER(), nullable=False),
    sa.Column('menu_id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('menu_nm', sa.VARCHAR(length=32), nullable=False),
    sa.Column('parent_nm', sa.VARCHAR(length=32), nullable=False),
    sa.Column('url_path', sa.VARCHAR(length=32), nullable=False),
    sa.Column('use_yn', sa.VARCHAR(length=1), nullable=True),
    sa.Column('created_dt', sa.DATETIME(), nullable=True),
    sa.Column('updated_dt', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('seq')
    )
    with op.batch_alter_table('sys_menus', schema=None) as batch_op:
        batch_op.create_index('ix_sys_menus_seq', ['seq'], unique=False)

    op.create_table('sys_role_menu',
    sa.Column('role_seq', sa.INTEGER(), nullable=False),
    sa.Column('menu_seq', sa.INTEGER(), nullable=False),
    sa.Column('use_yn', sa.VARCHAR(length=1), nullable=True),
    sa.Column('created_dt', sa.DATETIME(), nullable=True),
    sa.Column('updated_dt', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['menu_seq'], ['sys_menus.seq'], ),
    sa.ForeignKeyConstraint(['role_seq'], ['sys_roles.seq'], ),
    sa.PrimaryKeyConstraint('role_seq', 'menu_seq')
    )
    op.create_table('question',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('subject', sa.VARCHAR(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('create_date', sa.DATETIME(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_question_user_id_user'),
    sa.PrimaryKeyConstraint('id', name='pk_question')
    )
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.create_index('ix_question_id', ['id'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_nm', sa.VARCHAR(), nullable=False),
    sa.Column('password', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('create_date', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_user'),
    sa.UniqueConstraint('email', name='uq_user_email')
    )
    op.create_table('t_question',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('subject', sa.VARCHAR(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('create_date', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('todos',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('done', sa.BOOLEAN(), nullable=True),
    sa.Column('parent_id', sa.INTEGER(), nullable=True),
    sa.Column('c_date', sa.DATETIME(), server_default=sa.text("(datetime('now', 'localtime'))"), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['todos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.create_index('ix_todos_title', ['title'], unique=False)
        batch_op.create_index('ix_todos_id', ['id'], unique=False)

    op.create_table('sys_roles',
    sa.Column('seq', sa.INTEGER(), nullable=False),
    sa.Column('role_nm', sa.VARCHAR(length=32), nullable=False),
    sa.Column('use_yn', sa.VARCHAR(length=1), nullable=True),
    sa.Column('created_dt', sa.DATETIME(), nullable=True),
    sa.Column('updated_dt', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('seq')
    )
    with op.batch_alter_table('sys_roles', schema=None) as batch_op:
        batch_op.create_index('ix_sys_roles_seq', ['seq'], unique=False)

    # ### end Alembic commands ###
