"""empty message

Revision ID: aa313fa1e199
Revises: 1c7c1f307aad
Create Date: 2025-12-02 11:23:03.081929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa313fa1e199'
down_revision: Union[str, None] = '1c7c1f307aad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_index('ix_question_id')

    op.drop_table('question')
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.drop_index('ix_answer_id')

    op.drop_table('answer')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_nm', sa.VARCHAR(), nullable=False),
    sa.Column('password', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('create_date', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_user'),
    sa.UniqueConstraint('email', name='uq_user_email')
    )
    op.create_table('answer',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('create_date', sa.DATETIME(), nullable=False),
    sa.Column('question_id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], name='fk_answer_question_id_question'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_answer_user_id_user'),
    sa.PrimaryKeyConstraint('id', name='pk_answer')
    )
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.create_index('ix_answer_id', ['id'], unique=False)

    op.create_table('question',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('subject', sa.VARCHAR(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('create_date', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_question')
    )
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.create_index('ix_question_id', ['id'], unique=False)

    # ### end Alembic commands ###
